### ISSUE TITLE
Exception on PHP classnames used for $ref values

### ISSUE THREAD

**Issue by huy-tran** [fireproofsocks/dto#13]
Hi I am using your great library as part of the [Apiato](http://docs.apiato.io/)

I have following schemas:

```
<?php
class School extends \Dto\Dto
{
    protected $schema = [
        'type' => 'object',
        'properties' => [
            'location' => [
                '$ref' => Location::class
            ]
        ]
    ];
}

class Location extends \Dto\Dto
{
    protected $schema = [
        'type' => 'object',
        'properties' => [...],
        'required' => [....]
    ];
}
``` 

So when I initialized `$location = new Location([...])` I do get **Location** instance.

But then trying to assign **Location** to **School** as below:

```
$school = new School([...])
$school->location = $location;
```

It raised an exception of missing required values for **Location**

I read through **Wiki** and couldn't solve this one out. It's great if anyone can give shed me some lights!

Thanks in advanced!

**Comment by fireproofsocks** [comment]
Thanks for the bug report.  I just ran into this myself.  The problem is in the `ReferenceResolver`, in its `getPhpSchema()` method.  There's even a TODO note there:

```
// TODO: can we sniff this without instantiation?
$dto = new $ref();

if ($dto instanceof DtoInterface) {
     return $dto->getSchema();
}
```
The problem is that when the new class instance is instantiated, it IMMEDIATELY checks whether the object instance has the required properties it needs.  The reference resolver, however, doesn't know anything about the values ...  I have to think about this one.

**Comment by fireproofsocks** [comment]
Well... the best alternative I can come up with is to use Reflection.

You can edit the ReferenceResolver's code to the following:

```
    protected function getPhpSchema($ref)
    {
        // Instantiating the object would allow us to use the getSchema() method, but it also triggers validation
        $reflectionClass = new \ReflectionClass($ref);

        if ($reflectionClass->isSubclassOf(Dto::class)) {
            $properties = $reflectionClass->getDefaultProperties();
            return (array_key_exists('schema', $properties)) ? $properties['schema'] : [];
        }

        throw new InvalidReferenceException('Referenced classnames must implement DtoInterface');
    }
```

This avoids the problems with validation when instantiating a new object.  I will package this for a new release (**version 3.2.7**).  See `tests/UseCases/ReferenceTest.php` for a test that tests for this condition.

NOTE: I updated your comment to correct typos and to include the "type" parameter in the schema arrays (otherwise, no validation is triggered).

**Comment by huy-tran** [comment]
Hi @fireproofsocks . It's good to hear from you. And it's awesome that you are still active on this library. I love using DTO in my projects. I am looking forward to updating your library in the next release. Great work mate!
